### ISSUE TITLE
Empty cookie values

### ISSUE THREAD

**Issue by tsloughter** [elli-lib/elli_cookie#3]
Are empty cookie values valid in the spec? Based on https://tools.ietf.org/html/rfc2965

```
   av-pair     =     attr ["=" value]              ; optional value
```

I think it can... This became an issue as I try to move over a mochiweb app that I've discovered sends over cookies with empty values. Like:

```
"cookie1=; cookie2=" 
```

And elli cookies does:  `[N,V] = binary:split(NVP, <<"=">>, [trim])` which crashes in that case.

**Comment by yurrriq** [comment]
Sounds like we should definitely handle this. I've got a simple patch locally.

Should this be valid too?

```
"cookie1; cookie2"
```

/me reads spec

**Comment by tsloughter** [comment]
Great! And based on the spec it seems that should be valid too, yea.

**Comment by yurrriq** [comment]
Let me know if [0.2.7](https://github.com/elli-lib/elli_cookie/releases/tag/0.2.7) does The Right Thing™. If so I can publish it to Hex.

**Comment by tsloughter** [comment]
Yup, that worked, thanks!

**Comment by yurrriq** [comment]
Published to Hex (with `rebar.lock` update): https://hex.pm/packages/elli_cookie/0.2.8

**Comment by yurrriq** [comment]
Looks like somewhere between 0.1.7 and 0.2.8 I broke the Travis build at $WORK. It complains it can't find `elli/include/elli.hrl` and thus doesn't know what a `#req{}` is.
