### ISSUE TITLE
Add elli to applications

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli_cookie#4]
... or rewrite to obviate the need for `#req{}` at compile time.

**Comment by yurrriq** [comment]
Looks like it's only used in `parse/1`. We should use `elli:req()` in the spec anyway (which might depend on elli-lib/elli getting published to Hex) and the extra pattern match on the left hand side isn't strictly necessary.

**Comment by yurrriq** [comment]
I'm leaning toward using `elli:req()` in the `spec` and removing the extra pattern match from the left-hand side. With that I think we can move the `elli` dependency to the `test` profile, as it's done elsewhere, which would allow (read: require) users to provide their own version of Elli. Thoughts, @knutin, @tsloughter?

**Comment by tsloughter** [comment]
I would like the addition of `elli:req()` for the spec. I have the issue that in my app some of the types, like `timestamp()`, were already used in our application and conflicted :)

**Comment by yurrriq** [comment]
Cool. Do you have any insight on elli-lib/elli#1? Once that's solved, I think we can safely publish elli 1.1.0. I can't remember it 1.0.5 defines `elli:req()`.

**Comment by yurrriq** [comment]
The issue should be resolved for `elli_cookie` in [0.2.9](https://github.com/elli-lib/elli_cookie/releases/tag/0.2.9) (publishing to Hex shortly) and I've opened elli-lib/elli#5 to sort out the type naming collisions.
